package pl.edu.pg.eti.dragondestiny.playedgame.round.object;

public enum RoundState {

    WAITING_FOR_MOVE_ROLL,
    WAITING_FOR_FIELDS_TO_MOVE,
    WAITING_FOR_MOVE,
    WAITING_FOR_FIELD_OPTIONS,
    WAITING_FOR_FIELD_ACTION_CHOICE,

    // CARD FIELD:
    WAITING_FOR_CARD_DRAWN,
    // CARD FIELD - ITEM CARD:
    WAITING_FOR_CARD_TO_HAND,
    WAITING_FOR_CARD_TO_USED,

    // CARD FIELD - ENEMY CARD:
    WAITING_FOR_FIGHT_ROLL,
    WAITING_FOR_ENEMY_ROLL,
    WAITING_FOR_FIGHT_RESULT,
    WAITING_FOR_CARD_TO_TROPHIES,

    // ENEMY FROM FIELD:
    WAITING_FOR_ENEMIES_TO_FIGHT,

    // FIGHT WITH PLAYER:
    WAITING_FOR_PLAYER_TO_FIGHT,
    WAITING_FOR_ENEMY_PLAYER_ROLL,
    WAITING_FOR_CARD_THEFT,

    WAITING_FOR_BLOCK,
    WAITING_FOR_NEXT_ROUND,
    END_ROUND
}
