version: '3.1'

services:
 backend:
   # build: ./app
    image: backend:latest
    ports:
      - "9300:8080"
    depends_on:
      - database
    networks:
    - internal_network
    volumes:
     - type: volume
       source: FileStorage
       target: /uploads
 database:
    build: ./maria
    networks:
    - internal_network
    volumes:
     - type: volume
       source: my-db
       target: /var/lib/mysql
volumes:
 my-db:
 FileStorage:
networks:
  internal_network: