export enum RoundState{
    WAITING_FOR_MOVE_ROLL = 'WAITING_FOR_MOVE_ROLL', // SHOULD BLOCK FROM ANOTHER MOVE ROLL
    WAITING_FOR_FIELDS_TO_MOVE = 'WAITING_FOR_FIELDS_TO_MOVE', // FETCH POSSIBLE NEW POSITIONS
    WAITING_FOR_MOVE = 'WAITING_FOR_MOVE', // FIELD SHOULD DOWNLOAD INFO AND CHECK IF PLAYER CAN MOVE
    WAITING_FOR_FIELD_OPTIONS = 'WAITING_FOR_FIELD_OPTIONS', // FETCH FIELD OPTIONS
    WAITING_FOR_FIELD_ACTION_CHOICE = 'WAITING_FOR_FIELD_ACTION_CHOICE', // Get Round.PossibleOptions and choose one by sending selectRoundOption()

    // CARD FIELD:
    WAITING_FOR_CARD_DRAWN = 'WAITING_FOR_CARD_DRAWN', // LAUNCH NOTIFICATIONS.DRAW
    // CARD FIELD - ITEM CARD:
    WAITING_FOR_CARD_TO_HAND = 'WAITING_FOR_CARD_TO_HAND', // LAUNCH NOTIFICATIONS.DRAW equip() ?
    WAITING_FOR_CARD_TO_USED = 'WAITING_FOR_CARD_TO_USED', // LAUNCH NOTIFICATIONS.DRAW discard() ?

    // CARD FIELD - ENEMY CARD:
    WAITING_FOR_FIGHT_ROLL = 'WAITING_FOR_FIGHT_ROLL', // LAUNCH NOTIFICATIONS.FIGHT_ENEMY + rollCondition = true
    WAITING_FOR_ENEMY_ROLL = 'WAITING_FOR_ENEMY_ROLL', // LAUNCH NOTIFICATIONS.FIGHT_ENEMY + fight()
    WAITING_FOR_FIGHT_RESULT = 'WAITING_FOR_FIGHT_RESULT', // LAUNCH NOTIFICATIONS.FIGHT_ENEMY [new] ??
    WAITING_FOR_CARD_TO_TROPHIES = 'WAITING_FOR_CARD_TO_TROPHIES', // LAUNCH NOTIFICATIONS.FIGHT_ENEMY get_trophy()

    // ENEMY FROM FIELD:
    WAITING_FOR_ENEMIES_TO_FIGHT = 'WAITING_FOR_ENEMIES_TO_FIGHT', // LAUNCH NOTIFICATIONS.FIGHT_FIELD

    // FIGHT WITH PLAYER:
    WAITING_FOR_PLAYER_TO_FIGHT = 'WAITING_FOR_PLAYER_TO_FIGHT', // LAUNCH NOTIFICATIONS.FIGHT_PLAYER
    WAITING_FOR_ENEMY_PLAYER_ROLL = 'WAITING_FOR_ENEMY_PLAYER_ROLL', // LAUNCH NOTIFICATIONS.FIGHT_PLAYER + wait
    WAITING_FOR_CARD_THEFT = 'WAITING_FOR_CARD_THEFT', // LAUNCH NOTIFICATIONS.FIGHT_PLAYER + cardTheft = true

    WAITING_FOR_BLOCK = 'WAITING_FOR_BLOCK', // SHOW 'ACCEPT BLOCK TURN FOR X'
    WAITING_FOR_NEXT_ROUND = 'WAITING_FOR_NEXT_ROUND' // 'END TURN' CLICKABLE
}