export enum FieldType{
  TAKE_ONE_CARD = "TAKE_ONE_CARD",
  TAKE_TWO_CARDS = "TAKE_TWO_CARDS",
  LOSE_ONE_ROUND = "LOSE_ONE_ROUND",
  LOSE_TWO_ROUNDS = "LOSE_TWO_ROUNDS",
  BRIDGE_FIELD = "BRIDGE_FIELD",
  BOSS_FIELD = "BOSS_FIELD"
}
